name: binary releases

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  release:
    name: Release - ${{ matrix.platform.os }}
    runs-on: ${{ matrix.platform.os }}
    strategy:
      fail-fast: false
      matrix:
        platform:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            name: git-acm-linux-x86_64
          - os: macos-latest
            target: x86_64-apple-darwin
            name: git-acm-darwin-x86_64
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            name: git-acm-windows-x86_64.exe

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.platform.target }}

      - name: Build
        run: cargo build --release --target ${{ matrix.platform.target }}

      - name: Prepare Release
        shell: bash
        run: |
          # Get version from tag
          VERSION=${GITHUB_REF#refs/tags/}

          # Prepare binary with platform name
          if [ "${{ matrix.platform.os }}" = "windows-latest" ]; then
            cp "target/${{ matrix.platform.target }}/release/git-acm.exe" "${{ matrix.platform.name }}"
          else
            cp "target/${{ matrix.platform.target }}/release/git-acm" "${{ matrix.platform.name }}"
            chmod +x "${{ matrix.platform.name }}"
          fi

      - name: Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: ${{ matrix.platform.name }}
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}
