name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write # Explicitly grant permissions to create releases

jobs:
  release:
    name: Release - ${{ matrix.platform.os }}
    runs-on: ${{ matrix.platform.os }}
    strategy:
      fail-fast: false
      matrix:
        platform:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            binary_name: git-acm
            asset_name: git-acm-linux-amd64
          - os: macos-latest
            target: x86_64-apple-darwin
            binary_name: git-acm
            asset_name: git-acm-macos-amd64
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            binary_name: git-acm.exe
            asset_name: git-acm-windows-amd64.exe

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.platform.target }}

      - name: Build
        run: cargo build --release --target ${{ matrix.platform.target }}

      - name: Prepare binary (Unix)
        if: matrix.platform.os != 'windows-latest'
        run: |
          cd target/${{ matrix.platform.target }}/release/
          tar -czf ../../../${{ matrix.platform.asset_name }}.tar.gz ${{ matrix.platform.binary_name }}
          if [ "${{ matrix.platform.os }}" = "ubuntu-latest" ]; then
            sha256sum ../../../${{ matrix.platform.asset_name }}.tar.gz > ../../../${{ matrix.platform.asset_name }}.tar.gz.sha256
          else
            shasum -a 256 ../../../${{ matrix.platform.asset_name }}.tar.gz > ../../../${{ matrix.platform.asset_name }}.tar.gz.sha256
          fi

      - name: Prepare binary (Windows)
        if: matrix.platform.os == 'windows-latest'
        shell: pwsh
        run: |
          cd target/${{ matrix.platform.target }}/release/
          Compress-Archive -Path ${{ matrix.platform.binary_name }} -DestinationPath ../../../${{ matrix.platform.asset_name }}.zip
          Get-FileHash -Path ../../../${{ matrix.platform.asset_name }}.zip -Algorithm SHA256 | ForEach-Object { $_.Hash } > ../../../${{ matrix.platform.asset_name }}.zip.sha256

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: "${{ matrix.platform.asset_name }}.*"
          token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: false
          draft: false